image: docker:latest
services:
  - docker:dind

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

cache:
  key: ${CI_COMMIT_REF_SLUG}
#   key: tmp
  paths:
    - .m2/repository

stages:
 - build
 - deploy

maven-build:
  image: maven:3.8.5-openjdk-18-slim
  stage: build
  script:
    - echo ${CI_PROJECT_DIR}
    - mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - ./target/NiceSleep-1.2.1-SNAPSHOT-1.18.jar
    expire_in: 1 week

maven-deploy:
  image: alpine:latest
  stage: deploy
  dependencies: 
    - maven-build
  before_script:
    - apk update
    - apk add openssh sshpass
  script:
    - echo ${CI_PROJECT_DIR}
    - sshpass -p "${SSH_PASS}" scp -P 2225 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./target/NiceSleep-1.2.1-SNAPSHOT-1.18.jar staff@135.181.183.58:/files/build/
  only:
    - master