main: de.docm77.patreon.nicesleep.NiceSleep
name: NiceSleep
version: 1.1.0
author: tinnuadan@gmail.com
description: Nice Sleep Plugin
api-version: 1.17
commands:
  debug:
    description: Enables or disables fine logging
    usage: /debug [on|off]
    permission: nicesleep.debug
